---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: webapp.k8s.onegrid.xyz
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web-server-service
              port:
                number: 80